---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mbr-worker-config
  namespace: dongyu
data:
  MATRIX_HOMESERVER_URL: "http://synapse.dongyu.svc.cluster.local:8008"
  MATRIX_MBR_BOT_USER: "@mbr:dongyu.local"
  DY_MATRIX_ROOM_ID: "!fzuRnQYaDvsMJzwLMA:dongyu.local"
  DY_MQTT_HOST: "emqx-emqx-enterprise.emqx.svc.cluster.local"
  DY_MQTT_PORT: "1883"
  DY_MQTT_USER: ""
  DY_MQTT_PASS: ""
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
---
apiVersion: v1
kind: Secret
metadata:
  name: mbr-worker-secret
  namespace: dongyu
type: Opaque
stringData:
  MATRIX_MBR_BOT_ACCESS_TOKEN: "syt_bWJy_ZNQdUjBCnGAwrrpOSYzs_2S0abU"
